### ISSUE TITLE
Question: Why a profile *and* a role?

### ISSUE THREAD

**Issue by pfunkmallone** [Eilonh/s3crets_scanner#1]
I'm trying to understand the purpose of requiring both a profile in ~/.aws/credentials (which includes an AccessKey associated with an IAM user) but also a role?  Why do you switch from one identity (IAM User) to another (Role)? Why not simply attach the policy to the original IAM user?

My apologies if I'm asking a stupid question. I feel like I'm just missing something here....

**Comment by Eilonh** [comment]
Hey @pfunkmallone!
There are several ways to answer your questions - but it's not a "right or wrong" answer either, as it depends on the use cases and the number of accounts that you own.

Imagine that you have several accounts that you wish to scan - my approach is to create a **single** IAM user which can assume the same role in all of the accounts (trust relationship)
If I didn't use a role, then I'll need to create a user on each of the accounts, which is impractical.

Hope this answer your question :)
