### ISSUE TITLE
scanner not working when setup on my local [Not tried on EC2 instance however]

### ISSUE THREAD

**Issue by homerakshay** [Eilonh/s3crets_scanner#11]
Hi, I have set this up on my local and have run the scan keeping most of the crews specified in the rules.yml to have a catch. But nothing seems to work. Am I missing something here?

sh-3.2# python3 main.py -p aws-test -r S3ret-scanner -m internal 
   __________                __                                          
  / ___/__  /_____________  / /_   ______________ _____  ____  ___  _____
  \__ \ /_ </ ___/ ___/ _ \/ __/  / ___/ ___/ __ `/ __ \/ __ \/ _ \/ ___/
 ___/ /__/ / /__/ /  /  __/ /_   (__  ) /__/ /_/ / / / / / / /  __/ /    
/____/____/\___/_/   \___/\__/  /____/\___/\__,_/_/ /_/_/ /_/\___/_/     
                                                                         v1.0 
[+] Prerequisite checks passed
[+] Scanning for files which last modified since 2022-11-30 00:00:00+00:00
[+] Successfully loaded CSV file - /Users/akshaynayak/s3crets_scanner/csv/accounts.csv
[+] 1 accounts were loaded
[*] Analyzing public bucket - cf-templates-1eyurxhu5uyfk-us-east-1 in aws-test account
[*] Analyzing public bucket - s3rets in aws-test account
=== Scan completed ===

Any inputs will be much appreciated. 

Thanks.
Regards,
Akshay

**Comment by Eilonh** [comment]
Hey Akshay,
Please provide replications steps:
1. Is the cf and s3crets buckets are public?
2. Are they up and running or is it a local stack?
3. If so, do they contains any secrets? if so, what type?

Lastly, please provide the buckets URLs so we can reproduce.

Looking forward

**Comment by homerakshay** [comment]
Hi Eilonh, 

Thank you for getting back. Here are the list of answers to the questions you have put forward above.

1. The s3 buckets are all public, the setup is on my local MacBook
2. Its on my local, I have followed the steps to clone this repo, install the reqs and then set the role on IAM and run it locally which gives me the above pasted result.
3. I have put my dummy pen key and made it public [as the rules.yml] states we can have pet which it should catch. But have seen no luck.

Sharing across the bucket object URL : [The bucket "cf-templates-1eyurxhu5uyfk-us-east-1" is public completely]
https://cf-templates-1eyurxhu5uyfk-us-east-1.s3.amazonaws.com/akshay-ssh-rotate-key.pem

Looking forward to hear back at the earliest. 

Thanks once again.
Regards,
Akshay

**Comment by Eilonh** [comment]
Hi @homerakshay,

I added .pem file type.
Please see changes.

Please close the issue when confirmed.
