### ISSUE TITLE
AWS Creds check and async

### ISSUE THREAD

**Issue by InfiniteInsight** [Eilonh/s3crets_scanner#7]
Hi there!
I've written a function to check for a configuration file in the /.aws/ directory. I'll submit a PR for this soon after I have tested a bit further as well as making some documentation changes via comments. You can check out the dev branch of my fork if you'd like to see what I have done so far.

I have also noted that even with a 12 hour expiration or an expiration adjusted to max the STS token can expire. I would like to make some of these functions asynchronous so that the STS token isn't required to finish.

I would also like to help you expand the README.md file.

Hope this is all ok to do!

**Comment by Eilonh** [comment]
Hey @InfiniteInsight!
Contributors are always welcome!
Please issue a PR whenever you with too

**Comment by InfiniteInsight** [comment]
Ok, Will do later this week! Just wanted to check in as you said to ask about any major changes :)
