### ISSUE TITLE
Dependency conflicts

### ISSUE THREAD

**Issue by goosefraba** [Eilonh/s3crets_scanner#8]
Hey there,

I just wanted to check out the scanner but failed to let it run.
I followed the exact commands but got this error:

`Traceback (most recent call last):
  File "/XXXX/s3crets_scanner/main.py", line 1, in <module>
    import utils
  File "/XXXX/s3crets_scanner/utils.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

Any idea how to solve this?

All the best!

**Comment by Eilonh** [comment]
Hey @goosefraba!
It is likely that you have multiple python installation and pip is installing the dependencies to different version than the one you use to run the tool.
Try to see if ‘requests’ module is installed in your python path. Either way, this issue is  it related to the automation.
